"""Create transport orders from optimizer decisions."""

import logging
import math

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.transport_order import TransportOrder
from app.models.warehouse_config import WarehouseConfig
from app.services.optimizer import DispatchDecision

logger = logging.getLogger(__name__)


async def create_order_from_decision(
    session: AsyncSession,
    warehouse_id: str,
    decision: DispatchDecision,
    config: WarehouseConfig,
) -> TransportOrder:
    """
    Determine vehicle_type mix:
      - Fill with Furas first (minimize vehicle count)
      - Remaining with Gazels
    Create TransportOrder with status='draft'.
    """
    needed_capacity = decision.y_hat * config.safety_factor
    fura_count = math.floor(needed_capacity / config.fura_capacity) if config.fura_capacity > 0 else 0
    remaining = needed_capacity - fura_count * config.fura_capacity
    gazel_count = math.ceil(remaining / config.gazel_capacity) if remaining > 0 and config.gazel_capacity > 0 else 0

    total_count = fura_count + gazel_count
    total_capacity = fura_count * config.fura_capacity + gazel_count * config.gazel_capacity
    vehicle_type = "fura" if fura_count >= gazel_count else "gazel"

    order = TransportOrder(
        warehouse_id=warehouse_id,
        scheduled_departure=decision.scheduled_departure,
        vehicle_type=vehicle_type,
        vehicle_count=total_count,
        capacity_units=total_capacity,
        chosen_horizon=decision.optimal_horizon,
        optimizer_score=decision.optimal_score,
        status="draft",
        notes=f"Furas: {fura_count}, Gazels: {gazel_count}. Auto-generated by optimizer.",
    )

    session.add(order)
    await session.commit()
    await session.refresh(order)

    logger.info(
        "Created transport order %s for warehouse %s: %d vehicles (F=%d, G=%d), capacity=%.1f",
        order.id, warehouse_id, total_count, fura_count, gazel_count, total_capacity,
    )
    return order
